/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import static Cliente.tarjeta.btnCorreo;
import Coneccion.Conexion;
import Ventana.Login;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Squall
 */
public class tarjeta extends javax.swing.JInternalFrame {

    /**
     * Creates new form tarjeta
     */
    
    
    public tarjeta() {
          initComponents();
        Login e = new Login();

        btnCorreo.setText(e.dato);
    }
    public boolean validarnombre(String Correo) {
        Conexion objetoConexion = new Conexion();

        String query = "SELECT * FROM tarjeta WHERE Correo=?";
        try (PreparedStatement buscar
                = objetoConexion.getCnn().prepareStatement(query)) {
            buscar.setString(1, Correo);

            try (ResultSet rs = buscar.executeQuery()) {
                if (rs.next()) {
                    return true;
                }
            }

        } catch (Exception e) {
            System.out.println("Error email ya pidio." + e.getMessage());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCorreo = new javax.swing.JLabel();
        btnInformacion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnCorreo.setText("Email");

        btnInformacion.setText("Solicitar tarjeta");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        try {

            Conexion objetoConexion = new Conexion();

            Login en = new Login();
            en.setVisible(true);
            String Correo = btnCorreo.getText();

            String query = "insert into tarjeta (`Correo`)values('" + Correo + "')";
            state = objetoConexion.getCnn().createStatement();
            if (!validarnombre(Correo)) {
                    try {

                        int k = state.executeUpdate(query);
                        if (k > 0) {
                            JOptionPane.showMessageDialog(rootPane, "felicidades , Solicitud exitosa!");

                        } else {
                            JOptionPane.showConfirmDialog(rootPane, "lo sentimos, intente nuevamente!");
                        }
                    } catch (SQLException error) {
                        JOptionPane.showMessageDialog(rootPane, "error");
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "el email ya mando la solicitud");
            }

  
        } catch (SQLException ex) {
            Logger.getLogger(tarjeta.class.getName()).log(Level.SEVERE, null, ex);
         
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformacionActionPerformed
  ResultSet res;
  Statement state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel btnCorreo;
    private javax.swing.JButton btnInformacion;
    // End of variables declaration//GEN-END:variables
}
